Home task2
elenagronskaya/react-mentoring pull request #2
Opened 2022-07-01 15:31 UTC by elenagronskaya

2022-07-04 19:03 UTC, urakovaliaskar commented on src/components/Registration/Registration.jsx
> +				debugger;
remove

2022-07-04 23:06 UTC, urakovaliaskar commented on src/components/CourseInfo/CourseInfo.jsx
> +			<Link to='/courses' className={styles.link}>
move routes to const and reuse them

2022-07-04 23:13 UTC, urakovaliaskar commented on src/components/CourseInfo/CourseInfo.jsx
> +				&lt;Back to courses
Add space

2022-07-04 23:17 UTC, urakovaliaskar commented on src/components/Registration/Registration.jsx
> +			// setRegistration({ name: '', email: '', password: '' });
What is this for? remove.

2022-07-04 23:30 UTC, urakovaliaskar commented on src/common/Button/Button.jsx
> +	buttonText: PropTypes.string,
buttonText is used in every Button those it should be required prop. `PropTypes.string.isRequired`
For not required props define default value, for example:
`Button.defaultProps = {
    type: 'button'
}`

2022-07-04 23:32 UTC, urakovaliaskar commented on src/common/Button/Button.jsx
> +	buttonText: PropTypes.string,
Do it for all components with proptypes

2022-07-04 23:41 UTC, urakovaliaskar commented on src/components/CreateCourse/CreateCourse.jsx
> +	useEffect(() => {
add empty line, useEffect usually placed at the bottom of the functions

2022-07-04 23:41 UTC, urakovaliaskar commented on src/components/CreateCourse/CreateCourse.jsx
> +			return;
why do we need it? remove

2022-07-04 23:43 UTC, urakovaliaskar commented on src/components/CreateCourse/components/AuthorItem/AuthorItem.jsx
> +import PropTypes from 'prop-types';
to the top and add space to make a distinction between libraries and custom imports

2022-07-04 23:49 UTC, urakovaliaskar commented on src/components/Header/Header.jsx
> +				{userName && userName !== '' && (
if userName is truthy, then it cannot be "" (empty string), remove userName !== ''

2022-07-04 23:50 UTC, urakovaliaskar commented on src/components/Registration/Registration.jsx
> +			{errors.map((error) => {
simplify, remove unnecessary return

2022-07-04 23:51 UTC, urakovaliaskar commented on src/services/authService.js
> +	return await axios.post('http://localhost:4000/register', payload);
create const BASE_URL and reuse

2022-07-04 23:56 UTC, urakovaliaskar commented on src/services/courseService.js
> +			const author = { ...item };
Semantically speaking, it should be called course, not author

2022-07-04 23:58 UTC, urakovaliaskar commented on src/services/courseService.js
> +	if (courses.length === undefined) {
In which cases can this 2 conditions happen?

2022-07-05 00:00 UTC, urakovaliaskar commented on src/services/courseService.js
> +		.filter((item) => item.id.toLowerCase().includes(id.toLowerCase()))
use find, item.id.toLowerCase() === id.toLowerCase()

2022-07-05 00:05 UTC, urakovaliaskar commented on src/components/CourseInfo/CourseInfo.jsx
> +						{course == null ? '' : course.description}
course?.description || ''

2022-07-05 00:05 UTC, urakovaliaskar commented on src/components/CourseInfo/CourseInfo.jsx
> +						{course == null ? '' : course.description}
same for all

2022-07-05 00:06 UTC, urakovaliaskar requested changes
waiting for fixes

2022-07-05 14:30 UTC, AliaskarUrakovTR commented on src/components/CreateCourse/components/AuthorItem/AuthorItem.jsx
> +	showCourseButtonStyle: styles.button,
This is not AuthorItem's prop

2022-07-05 14:31 UTC, AliaskarUrakovTR commented on src/components/Login/Login.jsx
> +			return;
Why it is needed here?

2022-07-05 14:32 UTC, AliaskarUrakovTR commented on src/services/courseService.js
> +	if (foundCourse == null) {
if (!foundCourse)

2022-07-05 14:41 UTC, AliaskarUrakovTR approved these changes

2022-07-05 14:52 UTC, urakovaliaskar approved these changes

2022-07-05 14:53 UTC, merged