Home task3
elenagronskaya/react-mentoring pull request #3
Opened 2022-07-10 16:22 UTC by elenagronskaya

2022-07-12 15:24 UTC, urakovaliaskar commented on src/common/Button/Button.jsx
> +		{buttonText ? buttonText : <img src={imageLink} alt='button-text' />}
`buttonText || <img src={imageLink} alt='button-text' />`

2022-07-12 15:28 UTC, urakovaliaskar commented on src/components/CourseInfo/CourseInfo.jsx
> +		if (!availableAuthors || availableAuthors.length === 0) {
!availableAuthors?.length

2022-07-12 15:29 UTC, urakovaliaskar commented on src/components/CourseInfo/CourseInfo.jsx
> +		getCourseById(courseId);
you can remove brackets for this effect and write it in one line
`useEffect(() => getCourseById(courseId), [courseId]);

2022-07-12 15:31 UTC, urakovaliaskar commented on src/components/CourseInfo/CourseInfo.jsx
> +							{course?.authors.map((authorId) => {
course?.authors?.map

2022-07-12 15:32 UTC, urakovaliaskar commented on src/components/Courses/Courses.jsx
>  			return;
remove return

2022-07-12 15:36 UTC, urakovaliaskar commented on src/components/Courses/components/CourseCard/CourseCard.jsx
>  	let navigate = useNavigate();
use const

2022-07-12 15:38 UTC, urakovaliaskar commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +						onClick={() => courseDelete()}
`onClick={courseDelete}`

2022-07-12 15:44 UTC, urakovaliaskar commented on src/store/user/reducer.js
> +	token: '',
default value - empty string or token value from localStorage.

2022-07-12 16:07 UTC, urakovaliaskar commented on src/components/Header/Header.jsx
> +	const userData = useSelector(getUsersSelector);
remove userName state from App

2022-07-12 16:09 UTC, urakovaliaskar commented on src/components/Courses/Courses.jsx
> +		if (!userData.isAuth) {
If i refresh the page, i will be navigated to login page even though i have a token stored in localStorage

2022-07-12 18:14 UTC, urakovaliaskar requested changes
Waiting for fixes

2022-07-13 09:31 UTC, AliaskarUrakovTR commented on src/components/CourseInfo/CourseInfo.jsx
> +		getCourseById(courseId).then();
revert to how it was

2022-07-13 09:32 UTC, AliaskarUrakovTR commented on src/components/CourseInfo/CourseInfo.jsx
> +	useEffect(() => getCourseData);
Never call useEffect without 2nd argument

2022-07-13 09:33 UTC, AliaskarUrakovTR commented on src/components/Courses/components/CourseCard/CourseCard.jsx
> +						onClick={() => console.log('update')}
remove onClick if it does nothing

2022-07-13 09:35 UTC, AliaskarUrakovTR commented on src/services.js
> +		let data = response.data;
const { data } = response;

2022-07-13 09:36 UTC, AliaskarUrakovTR commented on src/services.js
> +		let response = null;
why do you need it?

2022-07-13 09:39 UTC, AliaskarUrakovTR requested changes
Waiting useEffect fix

2022-07-13 09:40 UTC, AliaskarUrakovTR commented on src/services.js
> +		const course = data.result;
check if result exists, with if or optional chaining

2022-07-14 16:59 UTC, urakovaliaskar approved these changes

2022-07-14 16:59 UTC, merged