Home task4
elenagronskaya/react-mentoring pull request #4
Opened 2022-07-18 10:06 UTC by elenagronskaya

2022-07-19 15:52 UTC, AliaskarUrakovTR commented on src/components/CourseForm/CourseForm.jsx
> +const CreateForm = () => {
Rename to CourseForm

2022-07-19 15:54 UTC, AliaskarUrakovTR commented on src/components/CourseForm/CourseForm.jsx
> +		store.dispatch(createCourseThunk({ ...selectedCourse }));
new course is not shown in the courses page after redirect, either save it in store in dispatch or refetch it again

2022-07-19 15:54 UTC, AliaskarUrakovTR commented on src/components/CourseForm/CourseForm.jsx
> +		const name = event.target.name;
const { name, value } = event.target

2022-07-19 15:55 UTC, AliaskarUrakovTR commented on src/components/CourseForm/CourseForm.jsx
> +						onChange={(event) => setValue(event)}
onChange={setValue}

2022-07-19 16:02 UTC, AliaskarUrakovTR commented on src/components/Login/Login.jsx
>  	const handleSubmit = async (e) => {
no await, remove async

2022-07-19 16:02 UTC, AliaskarUrakovTR commented on src/components/PrivateRoute/PrivateRoute.jsx
> +const PrivateRoute = ({ children, requiredRole }) => {
add prop types

2022-07-19 16:03 UTC, AliaskarUrakovTR commented on src/components/PrivateRoute/PrivateRoute.jsx
> +import React from 'react';
remove

2022-07-19 16:03 UTC, AliaskarUrakovTR commented on src/components/PrivateRoute/PrivateRoute.jsx
> +	const { role } = userData;
empty line after

2022-07-19 16:04 UTC, AliaskarUrakovTR commented on src/components/PrivateRoute/PrivateRoute.jsx
> +	const userData = useSelector(getUsersSelector);
const { role, isAuth } = useSelector(getUsersSelector);

2022-07-19 16:06 UTC, AliaskarUrakovTR commented on src/components/PrivateRoute/PrivateRoute.jsx
> +	return requiredRole === role ? children : <Navigate to={'/'} />;
it should navigate to /courses

2022-07-19 16:31 UTC, AliaskarUrakovTR commented on src/store/authors/api.js
> +import BASE_URL from '../../env';
This is completely wrong. Learn how to work with environment variables in React
https://create-react-app.dev/docs/adding-custom-environment-variables/
https://dev.to/felixdusengimana/environment-variables-in-reactjs-139l

2022-07-19 16:31 UTC, AliaskarUrakovTR requested changes
Waiting for fixes

2022-07-21 14:10 UTC, urakovaliaskar commented on src/components/PrivateRoute/PrivateRoute.jsx
> +	children: PropTypes.object,
children: PropTypes.node.isRequired

2022-07-21 14:17 UTC, AliaskarUrakovTR approved these changes

2022-07-21 14:17 UTC, merged